## Auditd Rules untuk Wazuh Agent (Agent 1)
## File: /etc/audit/rules.d/audit.rules
## Tujuan: Memantau semua eksekusi perintah di level kernel untuk deteksi Fileless Malware

## First rule - delete all
-D

## Increase the buffers to survive stress events.
-b 8192

## This determine how long to wait in burst of events
--backlog_wait_time 60000

## Set failure mode to syslog
-f 1

## Pantau semua eksekusi perintah (system call: execve) - 64-bit
-a always,exit -F arch=b64 -S execve -k audit-wazuh-c

## Pantau semua eksekusi perintah (system call: execve) - 32-bit
-a always,exit -F arch=b32 -S execve -k audit-wazuh-c
